SELECT COLUMN_NAME, character_set_name, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hbnb_dev_db' AND TABLE_NAME =
 'cities' AND COLUMN_NAME = 'id';
